### ISSUE TITLE
Does LKL be patched on LLVMLinux ?

### ISSUE THREAD

**Issue by alephman** [retrage/linux#2]
I want to separate  LKL and LLVMlinux,  but can't find the point where the first LKL patch imported on ?

**Comment by retrage** [comment]
Do you mention the code of LKL.js?
LKL is not related to LLVMLinux. It can be built with LLVM/Clang out-of-box.

**Comment by alephman** [comment]
Thanks for your reply.
I'm not sure whether my understanding for those steps is right or not:   
The LKL.js  dependents on Emscripten.  But the Emscripten is based on LLVM.  So the LKL have to be compiled by LLVM. As the upstream mainline linux kernel doesn't support  the LLVM compiler, we have to apply the LKL patch to LLVMLinux that is specific for LLVM.
So the steps for this project is:   LLVMLinux ---> apply LKL patch on LLVMLinux --->  using Emscripten to translate to  LKL.js.

**Comment by retrage** [comment]
LKL is not based on LLVMLinux. You can build LKL with LLVM/Clang without any patch. So, LKL.js is not patched for building LLVM.

**Comment by alephman** [comment]
Thanks for your reply
